version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: storetp_db
      MYSQL_ROOT_PASSWORD: motdepasse
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/storetp_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: motdepasse
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 9090

volumes:
  db_data: